### ISSUE TITLE
Field#.coordinates() required

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#43]
## Description

A method is required for fields that return the coordinates of a certain Field object.

## Problem to Solve

When filtering the Fields List of a Segment (e.g. to filter Fields of a certain type) the coordinates of the Fields cannot be derived from the Field itself.

## Proposed Solution

Add attribute coordinates to class Field or add a method Field#.coordinates().

## Use Cases

In order to calculate a path to a field of a certain type (e.g. Passenger or Goal) a Field object should hold it's coordinates.

## Alternatives

Calculation of paths by method Board#.find_nearest_field_types(). This method actually has a bug.

## Additional Context

We would prefer filtering the field list of the segments to calculate paths.

**Comment by maxblan** [comment]
Hi,
Thanks for the idea. Unfortunately, this goes against the idea of the data structure for this game. An attempt has been made to keep redundancy to a minimum, which is why the coordinates are stored via the space in the segments and there in the array and thus indirectly. It would therefore be superfluous to store the coordinates in the array itself. The only advantage would be the simpler determination of the coordinate. 

There is already a function that can convert the cube coordinate into the index for the array.
```rust
   // part if the CubeCoordinate struct
    pub fn array_x(&self) -> i32 {
        self.q.max(-self.s)
    }
    
    // part of the Segment struct
    fn array_coords(&self, coords: CubeCoordinates) -> CartesianCoordinate {
        CartesianCoordinate::new(coords.array_x() + 1, coords.y() + 2)
    }
```

Accordingly, if you want to determine the cube coordinate from the array index, this would be the following calculation:

$$
\begin{align*}
q &= x - y + 1 \\
r &= y - 2 \\
s &= -q - r
\end{align*}
$$

I've added a new method (`cube_coords`) to `Segment` which can do this calculation.
