### ISSUE TITLE
Closed Ship does not track number of collected passengers #47 STILL NOT SOLVED

### ISSUE THREAD

**Issue by kwollw** [maxblan/socha-python-client#48]
The problem still remains:

After ship has collected passenger:

print('current ship passengers:',self.gameState.current_ship.passengers)
print('other ship passengers:',self.gameState.other_ship.passengers)

output:

current ship passengers: 0
other ship passengers: 0

**Comment by maxblan** [comment]
To better assist you, please provide additional details about the context in which the issue is occurring. Specifically, I require information on the ship stats and how the segment looks like. 
Additionally, a debug log of a game where this issue occurs would be very helpful. 
To set the log level to debug, please use the following modified `Starter`: `Starter(logic=Logic(), log_level=logging.DEBUG)`

**Comment by kwollw** [comment]
solved in socha 2.2.2
